import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { NextUIProvider } from "@nextui-org/react";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider className="w-screen h-screen bg-gray-200 flex justify-center items-start py-4"><main className="w-[320px] sm:w-[400px] md:w-[800px]  h-full  ">{children}</main><ToastContainer autoClose={3000} theme="light" position="top-center"/></NextUIProvider>
        
      </body>
    </html>
  );
}
